# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocols.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocols.proto',
  package='scheduler',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fprotocols.proto\x12\tscheduler\")\n\x12StartModuleRequest\x12\x13\n\x0bmodule_name\x18\x01 \x01(\t\"\'\n\x13StartModuleResponse\x12\x10\n\x08response\x18\x01 \x01(\t2[\n\tScheduler\x12N\n\x0bStartModule\x12\x1d.scheduler.StartModuleRequest\x1a\x1e.scheduler.StartModuleResponse\"\x00\x62\x06proto3'
)




_STARTMODULEREQUEST = _descriptor.Descriptor(
  name='StartModuleRequest',
  full_name='scheduler.StartModuleRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='module_name', full_name='scheduler.StartModuleRequest.module_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=71,
)


_STARTMODULERESPONSE = _descriptor.Descriptor(
  name='StartModuleResponse',
  full_name='scheduler.StartModuleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='scheduler.StartModuleResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['StartModuleRequest'] = _STARTMODULEREQUEST
DESCRIPTOR.message_types_by_name['StartModuleResponse'] = _STARTMODULERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartModuleRequest = _reflection.GeneratedProtocolMessageType('StartModuleRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTMODULEREQUEST,
  '__module__' : 'protocols_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.StartModuleRequest)
  })
_sym_db.RegisterMessage(StartModuleRequest)

StartModuleResponse = _reflection.GeneratedProtocolMessageType('StartModuleResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTMODULERESPONSE,
  '__module__' : 'protocols_pb2'
  # @@protoc_insertion_point(class_scope:scheduler.StartModuleResponse)
  })
_sym_db.RegisterMessage(StartModuleResponse)



_SCHEDULER = _descriptor.ServiceDescriptor(
  name='Scheduler',
  full_name='scheduler.Scheduler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=114,
  serialized_end=205,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartModule',
    full_name='scheduler.Scheduler.StartModule',
    index=0,
    containing_service=None,
    input_type=_STARTMODULEREQUEST,
    output_type=_STARTMODULERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCHEDULER)

DESCRIPTOR.services_by_name['Scheduler'] = _SCHEDULER

# @@protoc_insertion_point(module_scope)
