# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protocols_pb2 as protocols__pb2


class SchedulerStub(object):
    """Scheduler service, used to schedule processes/tasks
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartModule = channel.unary_unary(
                '/scheduler.Scheduler/StartModule',
                request_serializer=protocols__pb2.StartModuleRequest.SerializeToString,
                response_deserializer=protocols__pb2.StartModuleResponse.FromString,
                )


class SchedulerServicer(object):
    """Scheduler service, used to schedule processes/tasks
    """

    def StartModule(self, request, context):
        """Starts a specific module specified by StartModuleRequest. Gets back
        a StartModuleResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartModule': grpc.unary_unary_rpc_method_handler(
                    servicer.StartModule,
                    request_deserializer=protocols__pb2.StartModuleRequest.FromString,
                    response_serializer=protocols__pb2.StartModuleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scheduler.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Scheduler(object):
    """Scheduler service, used to schedule processes/tasks
    """

    @staticmethod
    def StartModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/scheduler.Scheduler/StartModule',
            protocols__pb2.StartModuleRequest.SerializeToString,
            protocols__pb2.StartModuleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
